name: Hello World

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Echo Hello World
        run: echo "Hello World"
      - uses: ./postman/collections
        name: Run collection
        run: newman run postman/collections/New-Collection.json