name: Hello World

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Echo Hello World
        run: echo "Hello World"
      - name: directory
        run: ls